import React, { Component } from 'react';
import PropTypes from 'prop-types';
import { cardCount} from './CardDatabase';
import { magicCardFromIndex } from './MagicCard';

const CARD_POOL_DEAFULT_SIZE = 45;

//2020-07-11: The Epoch Year will be the starting year to generate db/lists from. 
// so if someone was born in 1985, their pools from 1985-EPOCH_YEAR will all be generated from available cards
// at the time of the epoch. So eventually, Setting epoch to 2020, but might test with 2010 or something to ensure correct
// functionality
const EPOCH_YEAR = 2020;

export class CardPool extends Component {
    constructor (props) {
        super(props);

        this.user_bday = props.user_bday;

        //2020-07-11: use seedrandom to create seed based on the user's inputted birthday
        // enventually, the seed will be generated by the user_bday concatenated with the pool's year, as
        // there would be one pool per year the user is alive.
        var seedrandom = require('seedrandom');
        seedrandom(this.user_bday, { global: true });

        if (props.year === undefined) {
            this.year = new Date().getFullYear();
        } else {
            this.year = props.year;
        }

        if (props.size === undefined || props.size <= 0) {
            this.size = CARD_POOL_DEAFULT_SIZE;
        } else {
            this.size = props.size;
        }

        this.state = {
            cards: [],
        };

        this.generatePool = this.generatePool.bind(this);
    }

    generatePool () {
        let cards = new Array(this.size).fill(undefined);
        console.log(cards);
        console.log(`Loading in ${cards.length} cards from a database of ${cardCount()} cards`);
        cards.forEach((_, index, self) => {
            console.log(`Loading card ${index}`);

            //2020-07-11: use Math.random() influenced by seedrandom and bdate to grab random cards
            // from the database
            self[index] = magicCardFromIndex(Math.floor(Math.random() * cardCount()), index);
        });

        this.setState({
            cards: cards
        });
    }

    componentDidMount () {
        if (this.state.cards.length === 0) {
            this.generatePool();
        }
    }

    render () {
        return (
        <div>
            <p>{this.year} pool for {this.user_bday}</p>

            <ol>{
                this.state.cards.map((card) => {
                    return <li key={card.key}>{card}</li>
                })
            }</ol>
        </div>
        );
    }
}

CardPool.propTypes = {
    user_bday: PropTypes.string.isRequired,
    year: PropTypes.number,
    size: PropTypes.number,
}
